export const EDIT_GRADE = "EDIT_GRADE";
export const SET_USER = "SET_USER";

export const GET_SYLLABUS="GET_SYLLABUS";
export const SELECTED_SYLLABUS="SELECTED_SYLLABUS";
export const EDIT_SYLLABUS="EDIT_SYLLABUS";

export const GET_EVENTS="GET_EVENTS"
export const DELETE_EVENT="DELETE_EVENT"
